### ISSUE TITLE
How to use this behind a reverse proxy?

### ISSUE THREAD

**Issue by ovizii** [radarlog/docker-pritunl#1]
I assume this bit "-p 9700:9700" could be removed, then placing the pritunl container in the same network as the reverse proxy and then reverse i.e. https://vpn.mydomain.tld to pritunl:9700 is the way to go?

**Comment by radarlog** [comment]
without mapping host ports to the docker ones, it should not work even for a reverse proxy mode, since proxy should somehow reach physically the container

**Comment by ovizii** [comment]
host port 443 is mapped to the reverse proxy which shares a docker network with the VPN container hence no mapping ports to the host system necessary.
