### ISSUE TITLE
Missing wireguard support?

### ISSUE THREAD

**Issue by ovizii** [radarlog/docker-pritunl#3]
Hi there, I am wondering if this container is using an older pritunl version without wireguard support? According to the pritunl manual there should be a checkbox to enable wireguard but I don't see it.

![image](https://user-images.githubusercontent.com/837902/88155588-8ae09480-cc08-11ea-8347-e5ea4ce97695.png)

**Comment by radarlog** [comment]
Just pushed a new version with wireguard support

**Comment by ovizii** [comment]
thanks, will give it a try soonest!
